# Generated by Django 4.2.1 on 2023-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='convenient_time',
            field=models.CharField(default='Всегда', max_length=50, verbose_name='Когда удобно принимать звонки'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='89064693578', max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Администратор', max_length=50, verbose_name='Роль'),
        ),
    ]
