# Generated by Django 4.2.1 on 2023-05-14 19:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user_convenient_time_user_patronymic_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ad', models.CharField(max_length=50, verbose_name='Название объявления')),
                ('description_ad', models.TextField(blank=True, verbose_name='Описание объявления')),
                ('date_pub', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
                ('number_views', models.IntegerField(verbose_name='Количество просмотров')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reg', models.CharField(max_length=50, null=True, verbose_name='Название региона')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_moder', models.DateField(default=datetime.date.today, verbose_name='Дата модерации')),
                ('publication', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.announcement')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50, null=True, verbose_name='Название города')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=50, verbose_name='Название категории')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='ID категории'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.cities', verbose_name='ID города'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
    ]
