# Generated by Django 4.2.1 on 2023-05-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_announcement_region_moderationad_cities_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status_ad',
            field=models.CharField(choices=[('draft', 'draft'), ('moderate', 'moderate'), ('rejected', 'rejected'), ('withdrawn', 'withdrawn'), ('active', 'active')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status_user',
            field=models.CharField(choices=[('blocked', 'blocked'), ('active', 'active'), ('waiting', 'waiting')], default='waiting', max_length=20),
        ),
    ]
